# Problem Statement 1: 


## Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [11]:
import numpy as np

def atv(vector,arg):
    result = []
    for i in vector:
        temp = []
        for j in range(arg):
            temp.append(i**(arg-j-1))
        result.append(temp)
    result = np.array(result)
    return result
l = list(map(int,input("Enter vector : ").strip().split()))
a = int(input('Enter a number: '))
print(atv(l,a))

Enter vector : 1 2 3
Enter a number: 3
[[1 1 1]
 [4 2 1]
 [9 3 1]]


# Problem Statement 2: 


# Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [18]:
def mov_avg(lst,win):
    result = []
    for i in range(len(lst)-win+1):
        temp = lst[i:i+win]
        #print(temp)
        result.append(sum(temp)//win)
    return result
print(mov_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3))

[5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]
